### ISSUE TITLE
E-Government Liberator 2.2 not working on LineageOS 22.1 (Android 15)?

### ISSUE THREAD

**Issue by Talki1** [Crazyphil/digitales-amt-liberator#28]
Dear Crazyphil!

After updating my Oneplus 6T from LineageOS 21 to 22.1 (22.1-20241231-NIGHTLY-fajita; Android-Version 15) your E-Government Liberator 2.2 stopped working.

- **Serviceportal Bund** (Version 1.8.0) says "Integritätsprüfung fehlgeschlagen: Offener Root-Zugang" ("Integrity check failed: Open root access")
- **Digitales Amt** (Version 3.3.1) loops on "Anmelden mit ID Austria / Handy-Signatur" ("Sign in with ID Austria / mobile phone signature")
- **eAusweise** (Version 4.1.14) stopped working even on LineageOS 21. Signing in with "Serviceportal Bund" was not possible anymore.

I am using LSPosed (1.9.3_mod (7244) - Zygisk; API Version 100) on Magisk 28.1 with Zygisk enabled. The apps "Serviceportal Bund" and "Digitales Amt" are not blocklisted by Magisk but activated in your Liberator.

The logfile:
`[ 2025-01-01T18:55:28.436    10275: 26825: 26825 I/LSPosed-Bridge  ] Loading legacy module it.kapfer.digitalesamt.liberator from /data/app/~~6PqRxzo-M7F0LsdcFDLHnw==/it.kapfer.digitalesamt.liberator-u24iejNI8yGkSUzJc6u3RQ==/base.apk
[ 2025-01-01T18:55:28.459    10275: 26825: 26825 I/LSPosed-Bridge  ]   Loading class it.kapfer.digitalesamt.liberator.ModuleMain
[ 2025-01-01T18:55:28.520    10275: 26825: 26825 I/LSPosed-Bridge  ] Detected Serviceportal Bund
[ 2025-01-01T18:55:28.522    10275: 26825: 26825 E/LSPosed-Bridge  ] java.lang.NoSuchFieldError: android.content.pm.PackageParser$PackageLite#versionCode
	at EVtXmbR.DZAdDK.JsBxsUW.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at EVtXmbR.DZAdDK.JsBxsUW.XposedHelpers.j(Unknown Source:0)
	at EVtXmbR.DZAdDK.JsBxsUW.b.get(Unknown Source:9)
	at java.util.Optional.orElseThrow(Optional.java:403)
	at EVtXmbR.DZAdDK.JsBxsUW.XposedHelpers.findField(Unknown Source:25)
	at EVtXmbR.DZAdDK.JsBxsUW.XposedHelpers.getIntField(Unknown Source:4)
	at it.kapfer.digitalesamt.liberator.ModuleMain.getPackageVersion(ModuleMain.kt:60)
	at it.kapfer.digitalesamt.liberator.ModuleMain.handleServicePortalBund(ModuleMain.kt:83)
	at it.kapfer.digitalesamt.liberator.ModuleMain.handleLoadPackage(ModuleMain.kt:50)
	at EVtXmbR.DZAdDK.JsBxsUW.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at EVtXmbR.DZAdDK.JsBxsUW.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at EVtXmbR.DZAdDK.JsBxsUW.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:320)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1134)
	at android.app.LoadedApk.getResources(LoadedApk.java:1382)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3466)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3457)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7463)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2449)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
`

Maybe there is a way to fix this?
Best regards,
Peter

**Comment by Crazyphil** [comment]
Thanks for the report! Seems like getting the version of an installed app (`getPackageVersion` in the code) has changed with Android 15.

I'll probably be able to look at that next week.

**Comment by Crazyphil** [comment]
@Talki1 Your problem should be fixed in PR #31, could you please download the APK that is linked there and confirm that it works?
After receiving your feedback, I will create an official release.

**Comment by Talki1** [comment]
Dear Crazyphil!

I tested your new version and can confirm that **Serviceportal Bund** (Version 1.8.0) and **Digitales Amt** (Version 3.3.1) are working perfect. Beside installing your new Liberator it was necessary to delete data and cache of both apps.

**eAusweise** (Version 4.1.14) is still not working. eAusweise asks for the fingerprint and then opens, but it is necessary to sign in with "ID Austria" to use the wallet. This is not possible because eAusweise crashes at this point.

Thanks a lot and best regards
Peter

**Comment by Crazyphil** [comment]
Good to hear that it works again, less good that eAusweise now crashes. However, that's actually strange because this app isn't even touched by E-Government Liberator.

I've just tried it on my phone still on LineageOS 21 (thankfully you have to re-activate eAusweise virtually whenever you need it) and the re-activation process went fine. Interestingly, in contrast to Digitales Amt, eAusweise detects an unlocked bootloader, but only warns about that and doesn't prevent you from using the app.

Do you have any other Xposed modules active that could influence eAusweise? Could you maybe get a logcat dump of the app at the point of it crashing so you get a stacktrace of the crash?

**Comment by sdrgeek** [comment]
There's another reason as to why eAusweise crashes. In the newest version of the app the android keystore is used. On TEE broken devices (like your 6T) the app therefore crashes. 
I'm having the same issue and had a go at it. This time I think that it's not fixable since spoofing key attestation doesn't fix the keystore.

**Comment by Crazyphil** [comment]
If that's the case, it sounds like an actual bug in the app to me, which should be reported to the developers. As it looks to me, eAusweise is designed to work on systems with unlocked bootloaders, and should therefore also run on devices without wiring hardware security.

For your situation, that would mean a downgrade to an older version of the eAusweise app should fix your problem.

**Comment by sdrgeek** [comment]
> If that's the case, it sounds like an actual bug in the app to me, which should be reported to the developers.

You're right, it shouldn't crash. It shouldn't throw a fatal exception an kill itself. 
One thing I noticed tho is that if you spoof key attestation, it no longer crashes but it will still show you an (in app) error message. Error code: A-09-TEA
That's why I think that they changed how the app stores it's certs.

> As it looks to me, eAusweise is designed to work on systems with unlocked bootloaders, and should therefore also run on devices without wiring hardware security.

Interesting, why do you think that?

**Comment by Crazyphil** [comment]
> > As it looks to me, eAusweise is designed to work on systems with unlocked bootloaders, and should therefore also run on devices without wiring hardware security.
> 
> Interesting, why do you think that?

Source: my own experiment two hours ago. As I mentioned above, I had to re-authenticate eAusweise to Digitales Amt. After that was done and I got directed back to the eAusweise app, it told me that my device has an unlocked bootloader and I should confirm that I want to continue using the app. To me, this means that the developers are aware that rooted devices pose a security risk, but in contrast to the developers of Digitales Amt, they are fine with that as long as the user knows about it.

**Comment by Talki1** [comment]
Dear Crazyphil, dear sdrgeek!

Thanks for your help to locate the problem with eAusweise. First a clarification: When I was writing about "the app crashes", I meant that the app was killing itself without any information.

Downgrading to eAusweise 4.0.9 doesn't help, as the app detects the new version and demands an update.

As sdrgeek mentioned it seems to be a TEE issue. Using "Tricky Store" fixes the crash, but eAusweise shows a "security-related logout" with code "K-02-TRU".

All in all I am happy that Crazyphil fixed the getPackageVersion-issue and Serviceportal Bund and Digitales Amt are working. 

Best regards
Peter

**Comment by Crazyphil** [comment]
Well then, I'd say that the core purpose of the change is fulfilled - Digitales Amt now works with Android 15. The problem with eAusweise seems to be unrelated to the module and might need a different fix. I'll release a new version of E-Government Liberator shortly.
